---

- name: create server config
  template:
    src: server.cfg.j2
    dest: "{{ urbanterror_directory }}/q3ut4/server.cfg"
    mode: 0660

- name: create mapcycle
  template:
    src: mapcycle.txt.j2
    dest: "{{ urbanterror_directory }}/q3ut4/mapcycle.txt"
    mode: 0660

...
