---

- name: install urbanterror files
  urbanterror_installer:
    url: "http://www.urbanterror.info/api/updaterv4"
    destination: "{{ urbanterror_directory }}"
    platform: Linux64
    updaterVersion: "{{ urbanterror_version }}"
  register: version_info
  notify:
    - restart urbanterror

- name: info
  debug:
    msg:
      - "{{ version_info }}"

- name: make sure that the engine is executable
  file:
    path: "{{ urbanterror_directory }}/{{ item }}"
    mode: 0750
  loop:
    - Quake3-UrT-Ded.x86_64
    - Quake3-UrT.x86_64

- name: install server.sh
  template:
    src: server.sh.j2
    dest: "{{ urbanterror_directory }}/server.sh"
    mode: 0750

- name: get custom maps
  get_url:
    url: "{{ item.src }}"
    dest: "{{ urbanterror_directory }}/q3ut4/"
    mode: 0640
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  loop: "{{ urbanterror_custom_maps }}"
  loop_control:
    label: "{{ item.name }}"

- name: create systemd unit file
  template:
    src: urbanterror.service.j2
    dest: /etc/systemd/system/urbanterror.service
    mode: 0644
  notify:
    - reload systemd

...
