---

- name: run installer   # noqa no-changed-when
  command: |
    {{ urbanterror_directory }}/updater.sh --quiet

- name: install server.sh
  template:
    src: server.sh.j2
    dest: "{{ urbanterror_directory }}/server.sh"
    mode: 0750

- name: get custom maps
  get_url:
    url: "{{ item.src }}"
    dest: "{{ urbanterror_directory }}/q3ut4/"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  loop: "{{ urbanterror_custom_maps }}"
  loop_control:
    label: "{{ item.name }}"

- name: create server config
  template:
    src: server.cfg.j2
    dest: "{{ urbanterror_directory }}/q3ut4/server.cfg"
    mode: 0660

- name: create mapcycle
  template:
    src: mapcycle.txt.j2
    dest: "{{ urbanterror_directory }}/q3ut4/mapcycle.txt"
    mode: 0660

- name: create systemd unit file
  template:
    src: urbanterror.service.j2
    dest: /etc/systemd/system/urbanterror.service
    mode: 0660

...
