---

- name: update facts
  ansible.builtin.setup:

- name: install dependencies
  ansible.builtin.package:
    name: "{{ urbanterror_dependencies }}"
    state: present

- name: create directory {{ urbanterror_directory }}
  ansible.builtin.file:
    path: "{{ urbanterror_directory }}"
    state: directory
    mode: "0750"

- name: create updater-cfg
  ansible.builtin.template:
    src: updater-cfg.j2
    dest: "{{ urbanterror_directory }}/updater-cfg"
    mode: "0660"

- name: copy updater.sh
  ansible.builtin.copy:
    src: updater.sh
    dest: "{{ urbanterror_directory }}/updater.sh"
    mode: "0750"

- name: get urbanterror engine list
  urbanterror_api:
    url: "http://www.urbanterror.info/api/updaterv4/"
    get: engine_list
    platform: Linux64
    updaterVersion: "{{ urbanterror_version }}"
  register: version_info

- name: engine list
  ansible.builtin.debug:
    msg:
      - "{{ version_info }}"
...
