---

- name: update apt cache
  apt:
    update_cache: true

- name: make sure ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name:
  package:
    name: "{{ urbanterror_dependencies }}"
    state: present

- name: create directory {{ urbanterror_directory }}
  file:
    path: "{{ urbanterror_directory }}"
    state: directory
    mode: 0750

- name: create updater-cfg
  template:
    src: updater-cfg.j2
    dest: "{{ urbanterror_directory }}/updater-cfg"
    mode: 0660

- name: copy updater.sh
  copy:
    src: updater.sh
    dest: "{{ urbanterror_directory }}/updater.sh"
    mode: 0750

...
