---

- name: restart urbanterror
  become: true
  ansible.builtin.service:
    name: urbanterror
    state: restarted

- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
